name: Build

on:
  pull_request:
  push:

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      -
        name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: build
